server:
  port: 7999
spring:
  application:
    name: gateway-api
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:8000/
    user:
      path: /user/**
      url: http://localhost:8001/
