spring:
  datasource:
    url: jdbc:mysql://47.92.133.46:3306/etcp_db?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
