server:
  port: 8000
  max-http-header-size: 102400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/dkm/resource/*/dao/mapper/*.xml
spring:
  profiles:
    active: test
  application:
    name: dkm-resource
  jmx:
    enabled: false
